--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/SalmonDE/Pathfinding-Example
branches:
- master
projects:
  Pathfinding-Example:
    path: ""
    libs:
    - src: SalmonDE/Pathfinding/Pathfinding
      version: ^0.1.0
...
