name: PathfinderExample
version: 1.1.0
author: SalmonDE
main: SalmonDE\PathfindingExample\Main
api: [4.0.0]
commands:
    a*:
        usage: /a* <1|2|calculate|repeat|clear> [2d]
        permission: astar
permissions:
    astar:
        default: op
